DROP DATABASE IF EXISTS `ssurvey`;

CREATE DATABASE `ssurvey`;

USE `ssurvey`

CREATE TABLE `survey` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;